18xx-maker/18xx-maker

src/data/games/1834.js, src/data/games/index.js, src/data/tiles.js
I'm not sure if you are interested in PRs or not, but I made this and figured I'd offer it up as another example. The only 2 things I couldn't figure out if they were possible or not were how to split the color on G14 so the right half is gray instead of red, and if it's possible to add color to a value amount which is needed for Antwerp(F5). Happy to update/fix any comments made as well if there are any standards that I didn't follow.
=> Adds 1834 support

src/Hex.jsx, src/Map.jsx, src/atoms/Hex.jsx
This allows for the entire map to be transparent. I also added in
the ability to allow for manual color setting for hexes.
=> Adds feature to specify rbg value for color and transparent map

src/data/games/1846.js
=> Fix Cairo city name

src/data/tiles.js
=> 1817 tiles

src/data/games/1848.json, src/data/games/1867.js, src/data/games/18Mex.json, src/data/games/index.js, src/data/logos/index.js, src/data/tiles/brown.json, src/data/tiles/gray.json, src/data/tiles/green.json, src/data/tiles/yellow.json
=> Adding 1867 map and tiles

src/atoms/Value.jsx, src/atoms/index.jsx, src/data/games/1834.json
In response to issue #58 
Outer border is kind of big because otherwise it wasn't clearly visible.
=> Add outer border color to value

src/data/games/1879.json, src/data/games/index.js
@kelsin This is my first game implementation, and I'd love some feedback on this.
=> Initial 1879 implementation.

src/data/games/1846.json, src/data/games/1867.json
=> Fix the token settings for 1846 and 1867

src/data/games/1867.json
* The CN still isn't right -- it should have red text on a white background. I'll probably have to create a logo to get it right. 
* Tokens with a white background end up looking bad on the reverse, since white on white is hard to read.
=> Update token colors for 1867 minor companies

src/Charters.jsx, src/Phase.jsx, src/data/games/1867.json
Minor companies frequently have different limits than Major (Stock) companies. Charters for minor companies should reflect this.
* Add minor phases to 1867
* Modify Charters to use minor phases for minor companies, if present
* Modify Phase table to include train prices, if present
=> Modify Charters to use minor phases for minor companies, if present

src/data/games/18CLE.json, src/data/games/index.js, src/data/tiles/brown.json, src/data/tiles/gray.json, src/data/tiles/green.json
This is a mostly functional 18CLE implementation. There is some cleanup that I would like to do before removing the wip tag and some accuracy checking.
=> Create 18CLE wip files

src/TileManifest.css
change width of quantity column to 0.5" and put the rest onto the ID column instead
=> fixing issue #105

src/atoms/Name.jsx, src/atoms/index.jsx
Set name's font style and weight (and family). Something I needed for my project and may be useful for others as well.
I added a new atom example.
=> Possibility to set name's font family, weight, and style

src/data/games/1834.json
Hey C,
Added icons for the doozy 1834 privates. Got any ideas for the remaining two?
Half price train and 'free' end-game train.
=> Added icons to some of the 1834 privates

src/data/tiles/brown.json, src/data/tiles/gray.json, src/data/tiles/green.json, src/data/tiles/yellow.json
these are just the tiles needed to push 1825's game file when it's time
=> adding some missing tiles, removing bogus alias

src/Config.jsx, src/data/games/18SS.json, src/data/games/18TK.json, src/data/games/index.js, src/data/themes/broggles1817.json, src/data/themes/broggles1836jr.json, src/data/themes/broggles1849.json, src/data/themes/broggles18EU.json, src/data/themes/broggles18TK.json, src/data/themes/brogglesmex.json, src/data/themes/companies/B18TK.json, src/data/themes/companies/broggles.json, src/data/themes/companies/index.js, src/data/themes/index.js
New game 18TK completed
18SS completed
and various themes added
=> First Pull request

src/data/games/public/18SW.json
a few tile corrections and addition of player info
=> 18SW tweaks

src/data/games/1882.json, src/data/tiles/brown.json, src/data/tiles/green.json
=> Initial commit of 1882 data. Token prices and neutral tokens still need

src/map/MapPaginated.jsx
=> Fixed map pagination issue (invalid size of the view)

src/Hex.jsx, src/data/games/public/1862.json, src/data/tiles/brown.json, src/data/tiles/green.json, src/data/tiles/yellow.json, src/market/Ledges.jsx, src/market/Market.jsx, src/market/MarketRoundTracker.jsx, src/market/Par.jsx, src/market/util.js
Solved #268. See specific commit messages for information on other fixes/improvements.
=> 1862 and related changes.

src/data/games/18TN.json
Fixes a new errors in the 18TN game data, and clarifies some of the privates and phase information.
=> 18TN: Fixes and clarifications.

src/data/games/public/18TNKY.json
Adds the expansion to 18TN, 18TN/KY, designed by KDD.
I've asked KDD if he could please add a comment here regarding the allowance of this game to be added.
=> 18TNKY: Add 18TNKY game.

src/tokens/Token.jsx
also icons with labels on tokens missing some scaling adjustments
=> shield tokens not scaling properly

src/Hex.jsx, src/atoms/Bridge.jsx, src/atoms/Diamond.jsx, src/atoms/Hexagon.jsx, src/atoms/index.jsx
adds hexagons like bridges, diamonds, and tunnels
adds scaling of all via "width"
fixes default font color which was broken
fixes strokeWidth such that 0 works
=> adding hexagons, fixing bridges, diamonds, and tunnels

src/Hex.jsx, src/atoms/Boomtown.jsx, src/atoms/Circle.jsx, src/atoms/index.jsx
This one works, so please do pull and merge it.
=> adding boomtowns

src/cards/Share.jsx
note that if you really wanted no logos on the card, you can still:
"tokenCount": 0
=> default should be to put a logo on the share cards

src/App.jsx, src/atoms/Boomtown.jsx, src/atoms/City.jsx, src/atoms/Name.jsx
removing boomtown path globals and using the above
adding ability to specify a straight name path per city/boomtown
addiing
=> adding ability to provide name paths directly

src/Charter.jsx, src/atoms/Value.jsx
While I realize this doesn't match the long-term plan, it at least lets me save this somewhere such that I don't have to re-merge it or lose it.
=> let a game specify the font to use for value/revenue circles

bin/b18.js, bin/print.js
b18 and print both do not work without this fix
=> paths busted by prior push 7c1a226b78e192b6df9deb6f335d4e064a15ce8f

src/atoms/Town.jsx, src/cards/Share.jsx, src/cards/index.jsx, src/data/games/1871BC.json, src/data/games/18SJ.json
=> update to 1871BC

src/data/games/1889.json
Updates a new link to the rulebook.
=> Update 1889 rulebook link in 1889.json

src/Legend.jsx, src/atoms/Value.jsx, src/cards/Private.jsx, src/data/tiles/gray.json, src/market/Cell.jsx, src/market/Market.jsx, src/pages/games/Tiles.jsx
lots of little fixes I've accumulated over the past few months
=> a bunch of small fixes/improvements

src/Hex.jsx, src/atoms/Id.jsx
Adds the displayID key that @th3tick provided the diff for.
=> Override ID with displayID key

.github/workflows/app.yml, .github/workflows/release.yml, .github/workflows/test.yml, release-please-config.json
ci: cleaner release title
ci: better release tagging and set prerelease to true
ci: fix windows summary
=> ci: add summaries for the test jobs

src/pages/elements/Tiles.jsx
=> fix(elements): improve tiles page to show more tiles and not error

electron/main/index.js, electron/preload/preload.js, package.json, pnpm-lock.yaml, src/components/Analytics.jsx, src/components/ExportButton.jsx, src/components/File.jsx, src/components/Root.jsx, src/components/TileFilters.jsx, src/components/nav/GameNav.jsx, src/components/pages/Home.jsx, src/components/pages/elements/Tiles.jsx, src/locales/en.json, src/util/analytics.js, src/util/analytics.test.js, src/util/query.js
=> feat(analytics): add self hosted plausible analytics

src/components/config/Input.jsx, src/components/config/UnitInput.jsx, src/hooks/config.js, src/hooks/index.js, src/hooks/validation.js, src/state/errors.js, src/state/index.js, src/state/store.js, src/util/input.js
Add error state to config input field when input is not valid according to schema.
=> feat(validation): add error state to config input field

src/components/atoms/Terrain.jsx, src/components/pages/elements/Atoms.jsx, src/data/icons/noenter.svg
Add no enter icon
[bgg request](https://boardgamegeek.com/thread/3207045/article/45190816#45190816)
=> feat(icons): add no enter icon
