18xx-maker/18xx-maker

src/cards/Train.jsx
This MR includes a small change which solves a z-index issue with the train's phase colors. Before the color was drawn last and covered up the price, now since the color is drawn first the text will be drawn on top and avoid the z-index issue.
Before:
After:
=> Moved <Color> component up to solve z-index issue

src/data/games/1868.js, src/data/games/index.js
Included is a data file for 1868 by Eddie Robbins and published by Winsome Games. 
Included is the map, charters, trains, tokens, shares, etc. Nothing major is omitted though I did have a few issues listed below, though I believe they are minor enough not to be an issue for those wishing to print and play the game.
- I set the map tiling to landscape mode, as it lead to more usable space for sheet.
- The private company text was paraphrased, though I tried to be as consistent as possible, I did have one rules question I posted to the Winsome yahoo group. If I get an answer that changes what I have, I'll push and update.
- This is my first attempt at creating a game data file, please let me know of any issues
- The grid system is off from the published map, which seems non-standard. This …
=> Initial data file for 1868

src/data/games/1868.js
Just a quick fix based on Kelsin's tip on getting a label to appear on a 4-city hex. Had to put a break in, but that's also how it appears on the published map itself.
=> Fix for label on Montevideo now showing

src/data/games/1834.json
Added missing hex, made text on cards more coherent.
=> 1834 minor corrections

src/data/games/1834.json
4T should be in a green phase and rusted by 6T, starting gray phase. 6T starts gray phase. Add "$" to $30 water hexes.
=> Fix 4T and 6T colors and $30 water hexes in 1834.

src/data/games/1867.json, src/data/tiles/brown.json, src/data/tiles/gray.json, src/data/tiles/green.json, src/data/tiles/yellow.json
* Update 1867 as follows:
* Add subtitle.
* Fix bank, rounds, turns.
* Start fixing stock market (not done).
* Fix trains.
* Define all public and private companies. (Minor companies not done yet).
* Fix tile manifest.
* Update yellow value for Maritime Provinces.
* Update tile manifest
* Add yellow tile 621.
* Add green tiles 204, 207, 637.
* Remove green tile X5 (it should be brown).
* Add brown tiles 801, 911.
* Rename brown tile X7 to X5.
* Rename brown tile X8 to X7.
* Add gray tiles 639, X8.
=> Update 1867 to match AAG version

src/data/games/1857.json
There were a few incorrect boxes in the market and I also took some opportunity to fix one of the private names and clarify some text.
=> Fix market errors and clarify private descriptions in 1857.

src/atoms/Value.jsx
I wanted to have a "+10" value and I realised that it didn't scale.
=> Value's size accords to the value's length

src/cards/Private.jsx, src/data/games/1867.json, src/index.css
Privates for 1867 have a minimum bid in addition to a price (face value). This extends the Private class to render a minimum bid above the price.
=> Add display elements for minimum bids

src/data/games/1834.json
I updated the the 1834 map:
- merged same offboard connections
- removed "B" label from Antwerp
- removed "e" from "Luxembourge"
- adjusted placement of city names so it's somehow coherent
=> 1834 update map

src/Phase.jsx
This allows for multiple rows in a cell in the train price column in the phases table.
=> Add formatCell to train prices in Phase.jsx.

src/data/games/1834.json
Removed $ references and tweaked the language a bit to make it less compressed. There is space on the cards.
=> Amended private companies text - remove $ refs

src/data/games/1834.json
Very minor tweak - I changed the Burbach Foundry icon to the tile which is more iconic. Looks better to my eye.
=> Change Burbach Foundry icon

src/Charter.jsx, src/Charters.jsx, src/cards/Private.jsx, src/cards/Share.jsx, src/cards/Train.jsx, src/cards/card.scss, src/data/schemas/game.schema.json
- Had an attempt at updating game.schema.json, after a quick skim of the JSON schema docs. Feel free to disregard this file or correct it if it's wrong.
- The "centre" share style needs styling adjustments if the card identifier is shown, as the text of the share percentage is too close. The number of shares and the percentage need more bottom padding. If you make this the same as the left/gmt variants, then it works, but might be too close to the horizontally coloured line. There looks like some simple adjustments that would allow the left/gmt variant to be removed entirely, but I'm unfamiliar with any ramifications this might cause, so have only made minimal stylistic changes.
- The card identifier styling might need adjustments, particularly with respect to how close it prints to the …
=> Add small card identifier text to bottom right of cards.

src/data/games/1832.json
Two revenue locations to fix, plus I think it is better to have the cost for the coal fields printed on the hex.
=> 1832 map fixes

src/atoms/Terrain.jsx, src/atoms/index.jsx
Something I needed and might be useful to others as well.
Usage:
```
{
"terrain": [
{
"type": "tree",
"cost": "$20",
"color": "green"
}
```
Updated atom examples.
=> Possibility to set terrain cost's color

src/cards/Train.jsx, src/cards/train.scss, src/data/games/18Test.json, src/data/schemas/game.schema.json
This adds a new property `tradeInPrice` to the train JSON element that provides for a trade in price. It will display under the train price in parenthesis, and a slightly smaller font. This can be used with the `description` property to provide more detail.
I've updated the game schema, but it's not 100% correct. Instead of it being a number, it should be whatever the `Currency` component takes. I'm not sure how to define the `type` as `whatever the Currency component takes`, so if that's possible, please advise or make the change yourself.
18Test has been updated with an example of usage.
=> Add train trade in pricing.

src/App.jsx
Mask width 75 comes right to the outer edge of the border, creating pixelwide artifacts on the outer edge. Mask width 74 comes right to the middle of the border, creating pixelwide artifacts on borderless edges. Mask width 74.5 appears to solve both issues.
These probably don't show up when printing, but are quite visible when viewing a pdf in the browser.
=> Fixed an issue with hex base color bleeding past the default border.

src/map/Title.jsx
Ideally, it would not only fall back if the stuff isn't specified, but also if the fontFamily doesn't exist.  I can't find a way to check that.
=> adding configurability for title, subtitle, and designer font, weight, and size

src/data/games/public/1836jr-30.json, src/data/games/public/1836jr-56.json
A few minor corrections for 1836jr:
- Correctly accent company name
- Add notes about home station hex cost to applicable charters
- Update the privates with more details and icons
- Add alternative text for one of the 1856 variant privates; rules are unclear how it should exactly behave. I hope it will be obvious to users to only use one of these privates (they are named the same).
=> 1836jr updates

src/cards/private.scss
A small change that aligns the text of private companies to prevent wrapping when icons are displayed.
Before:
After:
=> Align private text to prevent wrapping with icons are present.

src/Hex.jsx, src/atoms/MediumCity.jsx, src/atoms/OffBoardRevenue.jsx, src/atoms/index.jsx
- moving shapes to their own examples section and adding circles examples
- offBoardRevenues can do better for default text color
- adding properties from shapes to mediumCities (mostly to get width)
- missing property spread for mediumCityBorders
=> expanding mediumCities options, plus a few small tweaks

src/App.jsx, src/atoms/Boomtown.jsx
changing boomtowns to either be
- a centerTown with a dashed circle the size of a city
- a city with a dashed circle the size of a centerTown
changing boomtowns to do curved city names like cities
adding a new path for boomtown centerTowns, as the normal distance looks
too far away from the city
NOTE: These changes should be merged at the same time as the 18TraXX2020.json changes
I'll be pushing to 18xx-maker/games next, as they're interdependent.
=> boomtowns version 2

src/Config.jsx, src/Footer.jsx, src/Home.jsx, src/docs/logos.md, src/docs/overrides.md, src/docs/schema.md
I stumbled upon some dead links on the frontpage. sed to the rescue.
There are still some references in src/docs/running.md:
```
56:image](https://hub.docker.com/r/kelsin/18xx) that includes all games. Run the
61:docker run -it --rm -p 80:80 --name 18xx kelsin/18xx
74:       kelsin/18xx:develop
```
All other references to "kelsin" are mail or support links.
https://github.com/18xx-maker/18xx-maker/blob/master/src/data/tiles.js linked in src/Home.jsx is dead.
=> github.com/kelsin/18xx => github.com/18xx-maker/18xx-maker

src/cards/Private.jsx
Didn't see a way to color icons in Privates, added iconColor, like in Tokens. I used this in 18C2C pull request for the mining company
=> Use iconColor to color an icon in a Private

src/data/tiles/brown.json, src/data/tiles/green.json, src/data/tiles/yellow.json
Several funny-shaped cities and green town upgrades. Green 425, 426, 427 and Brown 435, 436 have their values and labels rotated because of how 1837's grid is laid out. Can fix if its a problem.
=> 1837 tiles

src/atoms/Value.jsx
diameter derived from the fontSize.  This restores the default, but
keeps the circle a tad tighter when the game defines a specific fontSize.
Eventually, allowing the circle size to be specified would be good,
but that's beyond the scope of fixing this bug.
=> the old default circle diameter was lost when making the circle

.github/workflows/test.yml
These tests already run as part of the merge queue, this will save some time in CI.
=> ci: do not run tests again on main branch

.github/workflows/test.yml
Since we have moved to pnpm and have a playwright
cache, this should be easier to manage
=> ci: run test.yaml on main pushes

electron.vite.config.js, electron/main/window.js, electron/preload/preload.js, package.json
This means that we have better security in electron. The main and
preload scripts now render to common JS files and the windows created by
electron are now all sandboxed. The main process is still written as ESM
but the renderer is not since it's one require line isn't a real require
line anyway so there really is no difference.
=> chore(app): turn sandbox mode on

src/components/Paginate.jsx, src/components/Phase.jsx, src/components/atoms/Name.jsx, src/components/tokens/Token.jsx
=> fix: allow charters with no trains and non-https contexts to work

src/components/pages/games/Game.jsx
Fix matching params with encoded game meta slug.
[discord issue](https://discord.com/channels/1302895372749770752/1302897137004052490/1313471879503282186)
[discord fix](https://discord.com/channels/1302895372749770752/1302897137004052490/1316021288413696001)
=> fix(game): match params slug with decoded meta slug
